services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_POSTGRES}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # networks:
    #   - transcendance
    restart: always

  # gateway:
  #   container_name: gateway
  #   build:
  #     context: ./gateway
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   # depends_on:
  #   #   - transcendance
  #   networks:
  #     - transcendance
  #   restart: always


  # nginx:
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   networks:
  #     - inception
  #   depends_on:
  #     - transcendance
  #   build:
  #     context: requirements/nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - "443:443"
  #   restart: always



  # nginx:
  #   build: ./nginx

  #   depends_on:
  #     - frontend
  #     - gateway
  #   networks:
  #     - transcendance



  # auth:
  #   build: ./services/auth
  #   env_file:
  #     - .env
  #   networks:
  #     - transcendance

  # user:
  #   build: ./services/user
  #   env_file:
  #     - .env
  #   networks:
  #     - transcendance

  # chat:
  #   build: ./services/chat
  #   env_file:
  #     - .env
  #   networks:
  #     - transcendance

  # game:
  #   build: ./services/game
  #   env_file:
  #     - .env
  #   networks:
  #     - transcendance

  # frontend:
  #   build: ./frontend
  #   networks:
  #     - transcendance


# networks:
#   transcendance:

volumes:
  postgres-data:
