services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: transcendance
    volumes:
      - postgres_data:/home/cauvray/data/postgres
    networks:
      - transcendance
    restart: always

  gateway:
    container_name: gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    env_file:
      - .env
    # depends_on:
    #   - transcendance
    networks:
      - transcendance
    restart: always


  # nginx:
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   networks:
  #     - inception
  #   depends_on:
  #     - transcendance
  #   build:
  #     context: requirements/nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - "443:443"
  #   restart: always



  # nginx:
  #   build: ./nginx

  #   depends_on:
  #     - frontend
  #     - gateway
  #   networks:
  #     - transcendance



  # auth:
  #   build: ./services/auth
  #   env_file:
  #     - .env
  #   networks:
  #     - transcendance

  # user:
  #   build: ./services/user
  #   env_file:
  #     - .env
  #   networks:
  #     - transcendance

  # chat:
  #   build: ./services/chat
  #   env_file:
  #     - .env
  #   networks:
  #     - transcendance

  # game:
  #   build: ./services/game
  #   env_file:
  #     - .env
  #   networks:
  #     - transcendance

  # frontend:
  #   build: ./frontend
  #   networks:
  #     - transcendance


networks:
  transcendance:

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/cauvray/data/postgres
